[project]
name = "comfyui-dropsend-node"
description = "Automatically upload ComfyUI output files to Dropbox with optional encryption. Supports real-time monitoring, cloud setups (RunPod), and includes cross-platform decryption scripts."
version = "1.0.3"
license = { file = "LICENSE" }
dependencies = ["requests", "python-dotenv", "watchdog", "dropbox", "cryptography"]

[project.urls]
Repository = "https://github.com/machinepainting/ComfyUI_DropSendNode"

[tool.comfy]
PublisherId = "machinepainting"
DisplayName = "DropSend Node"
Icon = ""
